# Generated by Django 2.2.7 on 2019-11-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='average',
        ),
        migrations.RemoveField(
            model_name='project',
            name='content',
        ),
        migrations.RemoveField(
            model_name='project',
            name='design',
        ),
        migrations.RemoveField(
            model_name='project',
            name='usability',
        ),
    ]
