# Generated by Django 2.2.7 on 2019-11-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20191125_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(upload_to='project_pic/'),
        ),
    ]
