# Generated by Django 2.2.7 on 2019-11-25 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20191125_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='design',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
