# Generated by Django 2.2.7 on 2019-11-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20191126_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
